version: '2'
services:
    chedemo-app:
        image: chedemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://chedemo-mysql:3306/chedemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    chedemo-mysql:
        extends:
            file: mysql.yml
            service: chedemo-mysql
